# Generated by Django 4.2.9 on 2026-03-31 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WardrobeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('category', models.CharField(choices=[('top', 'Верх (топы, рубашки, блузки)'), ('bottom', 'Низ (брюки, юбки, джинсы)'), ('dress', 'Платья и комбинезоны'), ('outerwear', 'Верхняя одежда'), ('shoes', 'Обувь'), ('bag', 'Сумки'), ('accessory', 'Аксессуары'), ('underwear', 'Бельё'), ('sportswear', 'Спортивная одежда'), ('other', 'Другое')], max_length=20, verbose_name='Категория')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Цвет')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Бренд')),
                ('season', models.CharField(choices=[('spring', 'Весна'), ('summer', 'Лето'), ('autumn', 'Осень'), ('winter', 'Зима'), ('all', 'Всесезонная')], default='all', max_length=10, verbose_name='Сезон')),
                ('image', models.ImageField(blank=True, null=True, upload_to='wardrobe/', verbose_name='Фото')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='Дата покупки')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Цена (₸)')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Любимая вещь')),
                ('times_worn', models.PositiveIntegerField(default=0, verbose_name='Раз надето')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wardrobe_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вещь гардероба',
                'verbose_name_plural': 'Гардероб',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('bio', models.TextField(blank=True)),
                ('face_shape', models.CharField(blank=True, choices=[('oval', 'Овальная'), ('round', 'Круглая'), ('square', 'Квадратная'), ('heart', 'Сердцевидная'), ('triangle', 'Треугольная')], max_length=20)),
                ('skin_tone', models.CharField(blank=True, choices=[('light', 'Светлый (I-II)'), ('medium', 'Средний (III-IV)'), ('dark', 'Тёмный (V-VI)'), ('olive', 'Оливковый')], max_length=20)),
                ('hair_color', models.CharField(blank=True, choices=[('blonde', 'Блонд'), ('brown', 'Шатен / Брюнет'), ('red', 'Рыжий'), ('black', 'Чёрный'), ('grey', 'Седой'), ('colored', 'Крашеный')], max_length=20)),
                ('body_type', models.CharField(blank=True, choices=[('hourglass', 'Песочные часы'), ('rectangle', 'Прямоугольник'), ('pear', 'Груша'), ('apple', 'Яблоко'), ('inverted', 'Перевёрнутый треугольник')], max_length=20)),
                ('preferred_style', models.CharField(blank=True, choices=[('casual', 'Casual'), ('classic', 'Classic'), ('sport', 'Sport'), ('boho', 'Boho'), ('business', 'Business'), ('romantic', 'Romantic')], max_length=20)),
                ('monthly_budget', models.PositiveIntegerField(default=0, help_text='Бюджет в тенге (₸)')),
                ('color_season', models.CharField(blank=True, help_text='Напр: Осень/Тёплый', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
        migrations.CreateModel(
            name='StyleTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('tip_type', models.CharField(choices=[('makeup', '💄 Макияж'), ('wardrobe', '👗 Гардероб'), ('accessory', '💎 Аксессуары'), ('color', '🎨 Цвет'), ('general', '✨ Общее')], default='general', max_length=20, verbose_name='Тип')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='Теги')),
                ('is_saved', models.BooleanField(default=True, verbose_name='Сохранено')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='style_tips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Совет стилиста',
                'verbose_name_plural': 'Советы стилиста',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MakeupSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Название образа')),
                ('active_makeup', models.JSONField(default=list, verbose_name='Активный макияж')),
                ('lip_color', models.CharField(default='#c0392b', max_length=10, verbose_name='Цвет губ')),
                ('ai_feedback', models.TextField(blank=True, verbose_name='AI анализ')),
                ('snapshot', models.ImageField(blank=True, null=True, upload_to='makeup_snapshots/', verbose_name='Снимок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='makeup_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сессия макияжа',
                'verbose_name_plural': 'Сессии макияжа',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_type', models.CharField(choices=[('wardrobe', '👗 Гардероб'), ('capsule', '📦 Капсула'), ('colors', '🎨 Цвета'), ('full', '✨ Полный анализ')], default='full', max_length=20, verbose_name='Тип')),
                ('input_params', models.JSONField(default=dict, verbose_name='Входные параметры')),
                ('result', models.JSONField(default=dict, verbose_name='Результат AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Рекомендация',
                'verbose_name_plural': 'AI Рекомендации',
                'ordering': ['-created_at'],
            },
        ),
    ]
