# Generated by Django 4.2.9 on 2026-03-31 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stylist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='monthly_budget',
            field=models.PositiveIntegerField(default=0, help_text='Бюджет в сомах (сом)'),
        ),
        migrations.AlterField(
            model_name='wardrobeitem',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='Цена (сом)'),
        ),
    ]
