# Generated by Django 4.2.9 on 2026-04-15 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_wardrobe_categories(apps, schema_editor):
    WardrobeItem = apps.get_model("stylist", "WardrobeItem")
    mapping = {
        "top": "shirt_long",
        "bottom": "pants_classic",
        "dress": "dress_casual",
        "outerwear": "jacket",
        "shoes": "sneakers",
        "bag": "bag_daily",
        "accessory": "accessory_jewelry",
        "sportswear": "sports_set",
        "other": "other",
    }
    for legacy, replacement in mapping.items():
        WardrobeItem.objects.filter(category=legacy).update(category=replacement)


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stylist", "0002_alter_userprofile_monthly_budget_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("user", "Пользователь"), ("assistant", "Ассистент")],
                        max_length=20,
                        verbose_name="Роль",
                    ),
                ),
                ("content", models.TextField(verbose_name="Сообщение")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Сообщение чата",
                "verbose_name_plural": "Сообщения чата",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChatSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Название диалога"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Чат-сессия",
                "verbose_name_plural": "Чат-сессии",
                "ordering": ["-updated_at", "-created_at"],
            },
        ),
        migrations.RemoveField(
            model_name="styletip",
            name="user",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="body_type",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="color_season",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="face_shape",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="hair_color",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="monthly_budget",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="preferred_style",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="skin_tone",
        ),
        migrations.RemoveField(
            model_name="wardrobeitem",
            name="price",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="city_climate",
            field=models.CharField(
                blank=True, max_length=160, verbose_name="Город / климат"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="favorite_occasions",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Любимые случаи"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="lifestyle",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Образ жизни"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="occupation",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Роль / занятие"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="sizes_note",
            field=models.TextField(blank=True, verbose_name="Заметка о размерах"),
        ),
        migrations.RunPython(migrate_wardrobe_categories, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="wardrobeitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("shirt_short", "Рубашка с коротким рукавом"),
                    ("shirt_long", "Рубашка с длинным рукавом"),
                    ("tshirt", "Футболка"),
                    ("top", "Топ"),
                    ("blouse", "Блузка"),
                    ("jeans_ankle", "Джинсы до щиколотки"),
                    ("jeans_full", "Джинсы полной длины"),
                    ("pants_classic", "Классические брюки"),
                    ("pants_wide", "Широкие брюки"),
                    ("skirt_mini", "Мини-юбка"),
                    ("skirt_midi", "Юбка миди"),
                    ("dress_casual", "Повседневное платье"),
                    ("dress_evening", "Вечернее платье"),
                    ("jumpsuit", "Комбинезон"),
                    ("jacket", "Куртка"),
                    ("blazer", "Пиджак"),
                    ("coat", "Пальто"),
                    ("trench", "Тренч"),
                    ("hoodie", "Худи"),
                    ("sweater", "Свитер"),
                    ("sneakers", "Кроссовки"),
                    ("heels", "Туфли на каблуке"),
                    ("boots", "Ботинки"),
                    ("loafers", "Лоферы"),
                    ("sandals", "Сандалии"),
                    ("bag_daily", "Повседневная сумка"),
                    ("bag_evening", "Вечерняя сумка"),
                    ("accessory_jewelry", "Украшения"),
                    ("accessory_belt", "Ремень"),
                    ("accessory_hat", "Головной убор"),
                    ("accessory_scarf", "Шарф / платок"),
                    ("accessory_watch", "Часы"),
                    ("accessory_glasses", "Очки"),
                    ("sports_set", "Спортивный комплект"),
                    ("underwear", "Бельё"),
                    ("other", "Другое"),
                ],
                max_length=32,
                verbose_name="Категория",
            ),
        ),
        migrations.DeleteModel(
            name="MakeupSession",
        ),
        migrations.DeleteModel(
            name="StyleTip",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages",
                to="stylist.chatsession",
            ),
        ),
    ]
