# Generated by Django 4.2.9 on 2026-04-17 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("stylist", "0003_chatmessage_chatsession_remove_styletip_user_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        verbose_name="Название коллекции (например, Streetwear)",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Коллекция",
                "verbose_name_plural": "Коллекции",
            },
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_limit_reset",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="messages_sent_today",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="outfits_generated_today",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="plan_type",
            field=models.CharField(
                choices=[("free", "Базовый"), ("pro", "Pro")],
                default="free",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="airecommendation",
            name="rec_type",
            field=models.CharField(
                choices=[
                    ("wardrobe", "👗 Гардероб"),
                    ("capsule", "📦 Капсула"),
                    ("colors", "🎨 Цвета"),
                    ("full", "✨ Полный анализ"),
                    ("grwm", "🔥 Генерация GRWM"),
                ],
                default="full",
                max_length=20,
                verbose_name="Тип",
            ),
        ),
        migrations.CreateModel(
            name="Look",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Название образа"
                    ),
                ),
                ("ai_feedback", models.TextField(blank=True, verbose_name="Отзыв AI")),
                (
                    "rating",
                    models.PositiveIntegerField(default=0, verbose_name="Оценка"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="looks",
                        to="stylist.collection",
                        verbose_name="Коллекция",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(
                        related_name="looks",
                        to="stylist.wardrobeitem",
                        verbose_name="Вещи в образе",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="looks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Образ",
                "verbose_name_plural": "Образы",
            },
        ),
    ]
